query GetWorkflowRuns($owner: String!, $name: String!) {
  repository(owner: $owner, name: $name) {
      name
      owner {
      login
      }
      refs(refPrefix: "refs/heads/", first: 100) {
      nodes {
          name
          target {
          ... on Commit {
              history(first: 10) {
              nodes {
                  oid
                  messageHeadline
                  author {
                  name
                  user {
                      login
                  }
                  }
                  committedDate
                  checkSuites(first: 20) {
                  nodes {
                      id
                      conclusion
                      status
                      workflowRun {
                      id
                      databaseId
                      runNumber
                      event
                      workflow {
                        name
                      }
                      createdAt
                      url
                      }
                      checkRuns(first: 10) {
                      totalCount
                      nodes {
                        name
                        conclusion
                        status
                        startedAt
                        completedAt
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
