name: Run pre-commit

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.github/*'
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read
  pull-requests: write

env:
  DAGGER_VERSION: 0.18.14

# Just a test comment
jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Run build module
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: ${{ env.DAGGER_VERSION }}
          call: --commit ${{ github.sha }} build
